project_id = "pelykusygwjztlqwljko"

[api]
enabled = true
port = 54321
schemas = ["public", "storage", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 54322
shadow_port = 54320
major_version = 15

[db.pooler]
enabled = false
port = 54329
pool_mode = "transaction"
default_pool_size = 20
max_client_conn = 100

[realtime]
enabled = true
ip_version = "ipv4"
port = 54323
max_header_length = 4096

[studio]
enabled = true
port = 54323
api_url = "http://127.0.0.1:54321"
openai_api_key = "env(OPENAI_API_KEY)"

[inbucket]
enabled = true
port = 54324
# Inbucket port for tests and local development
smtp_port = 54325
pop3_port = 54326

[storage]
enabled = true
file_size_limit = "50MiB"
image_transformation = { enabled = true }

[auth]
enabled = true
site_url = "http://127.0.0.1:3000"
additional_redirect_urls = ["https://127.0.0.1:3000"]
jwt_expiry = 3600
enable_signup = true
enable_confirmations = false
enable_recoveries = true
enable_email_change_confirmations = true
enable_phone_change_confirmations = true

[auth.email]
enable_signup = true
double_confirm_changes = true
enable_confirmations = false
template_confirmation = "./supabase/templates/confirmation.html"
template_invite = "./supabase/templates/invite.html"
template_magic_link = "./supabase/templates/magic-link.html"
template_recovery = "./supabase/templates/recovery.html"
template_email_change = "./supabase/templates/email-change.html"

[auth.sms]
enable_signup = true
enable_confirmations = false
template_confirmation = "./supabase/templates/confirmation.txt"
template_invite = "./supabase/templates/invite.txt"
template_magic_link = "./supabase/templates/magic-link.txt"
template_recovery = "./supabase/templates/recovery.txt"

[functions.generate-predictions]
verify_jwt = true

[functions.generate-growth-playbook]
verify_jwt = true

[edge_runtime]
enabled = true
policy = "per_worker"
inspector_port = 8083